permalink: /posts/:title/
name: Abhishek Das
description: Machine learning researcher. On a quest to build real artificial intelligence.
url: http://abhishekdas.com
markdown: redcarpet
include: ['_pages']