encoding: utf-8
name: Abhishek Das
url: http://abhishekdas.com
author:
  name: Abhishek Das
  email: das.abhshk@gmail.com
description: Machine learning researcher. On a quest to build real artificial intelligence.
permalink: /posts/:title/
include: ['_pages']
